export const DI_SERVICE_METADATA_KEY = 'PAC_SERVICE_METADATA';
export const DI_CONTRIBUTION_METADATA_KEY = 'PAC_CONTRIBUTION_METADATA';
export const DI_UNIT_MODULE_METADATA_KEY = 'PAC_UNIT_MODULE_METADATA';
